import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Button from '../../public/'
const Home: NextPage = () => {
  return (
    <div className={styles.body}>
      <Head>
        <title>Vlink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.background}>
          <div className={styles.webtopbox} >
          </div>
            <div className={styles.flexbox} >
              <div className={styles.btncontainer}>
                  <div className={styles.btn} >
                    <a  href="#">
                    <Image
                      src="/../public/Button.png"
                      alt="Picture of the author"
                      layout="intrinsic"
                      width={600}
                      height={150}
                    />
                     </a>
                    
                  </div>
                  <div className={styles.slogan}>圈子里的事，来 Vlink 里讲</div>
              </div>
            </div>
       </div>
      </div>
      

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
